MeuBlog/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('blog.urls')),
]

# Direcionamento do erro 404
handler404 = "blog.views.handler404"

blog/urls.py
from django.urls import path
from .views import Home, Posts, PostDetail, AddPost, UpdatePost, DeletePost, AddComment, Categories, CategoryDetail


urlpatterns = [
    path('', Home.as_view(), name="home"),
    path('posts/', Posts.as_view(), name="posts"),
    path('post/<int:pk>', PostDetail.as_view(), name="post-detail"),
    path('add_post/', AddPost.as_view(), name="add_post"),
    path('post/edit/<int:pk>', UpdatePost.as_view(), name="update_post"),
    path('post/<int:pk>/delete', DeletePost.as_view(), name="delete_post"),
    path('post/<int:pk>/comment', AddComment.as_view(), name="add_comment"),
    path('posts/categories/', Categories.as_view(), name="categories"),
    path('posts/categories/<int:cat_id>', CategoryDetail, name="category-detail"),
]

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from datetime import datetime, date

class Category(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField()

    def __str__(self):
        return self.name

class Post(models.Model):
    title = models.CharField(max_length=255)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    imageURL = models.URLField(default = 'https://www.ncenet.com/wp-content/uploads/2020/04/No-image-found.jpg')
    datetime = models.DateTimeField(auto_now_add=True)
    body  = models.TextField()
    category = models.ManyToManyField(Category, default="Treino")

    def __str__(self):
        return self.title + ' | ' + str(self.author.first_name) + '  ' + str(self.author.last_name)

    def get_absolute_url(self):
        return reverse('post-detail', kwargs={'pk': self.pk})

class Comment(models.Model):
    post = models.ForeignKey(Post, related_name='comments', on_delete=models.CASCADE)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    datetime = models.DateTimeField(auto_now_add=True)
    body  = models.TextField()

    def __str__(self):
        return '%s - %s' %(self.post.title, self.author)

blog/forms.py
from django import forms
from .models import Post, Comment, Category

choices = Category.objects.all().values_list('name','name')
cat_list = []

for cat in choices:
    cat_list.append(cat)

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('title', 'author', 'category', 'imageURL', 'body')

        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control form-control-lg', 'placeholder': 'O título da sua postagem', 'label': 'alo'}),
            'author': forms.Select(attrs={'class': 'form-control'}),
            'category': forms.CheckboxSelectMultiple(choices=cat_list),
            'imageURL': forms.URLInput(attrs={'class': 'form-control', 'placeholder': 'Link de uma imagem associada à postagem'}),
            'body': forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'O conteúdo da postagem'}),
        }

class EditForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('title', 'category', 'imageURL', 'body')

        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control form-control-lg', 'placeholder': 'O título da sua postagem', 'label': 'alo'}),
            'category': forms.CheckboxSelectMultiple(choices=cat_list),
            'imageURL': forms.URLInput(attrs={'class': 'form-control', 'placeholder': 'Link de uma imagem associada à postagem'}),
            'body': forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'O conteúdo da postagem'}),
        }

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('author', 'body')

        widgets = {
            'author': forms.Select(attrs={'class': 'form-control'}),
            'body': forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'O conteúdo do comentário'}),
        }

blog/views.py
from django.shortcuts import render, get_object_or_404
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from .models import Post, Comment, Category
from .forms import PostForm, EditForm, CommentForm
from django.urls import reverse_lazy

def handler404(request, exception):
    return render(request, '404.html')

class Home(ListView):
    model = Post
    template_name = 'home.html'

class Posts(ListView):
    model = Post
    template_name = 'posts.html'
    ordering = ['-datetime'] # coloca os posts mais recentes primeiro

class PostDetail(DetailView):
    model = Post
    template_name = 'post_details.html'

class AddPost(CreateView):
    model = Post
    form_class = PostForm
    template_name = 'add_post.html'

class UpdatePost(UpdateView):
    model = Post
    form_class = EditForm
    template_name = 'update_post.html'
    #fields = ('title', 'imageURL', 'body')

class DeletePost(DeleteView):
    model = Post
    template_name = 'delete_post.html'
    success_url = reverse_lazy('posts')

class AddComment(CreateView):
    model = Comment
    form_class = CommentForm
    template_name = 'add_comment.html'
    #fields = '__all__'

    def form_valid(self, form):
        form.instance.post_id = self.kwargs['pk']
        return super().form_valid(form)
    
    def get_success_url(self):
        return reverse_lazy('post-detail', kwargs={'pk': self.kwargs['pk']})

class Categories(ListView):
    model = Category
    template_name = 'categories.html'
    fields = '__all__'

def CategoryDetail(request, cat_id):
    cat = get_object_or_404(Category, pk=cat_id)
    return render(request, 'category_details.html', {'cat':cat})

blog/templates/add_comment.html
{% extends 'base.html' %}
{% block title%} Adicionar Comentário {% endblock %}

{% block content %}

<h1>Adicionar Comentário</h1>
<br><br>

<form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button class="btn btn-success">Comentar</button>

{% endblock %}

blog/templates/add_post.html
{% extends 'base.html' %}
{% block title%} Criar Postagem {% endblock %}

{% block content %}

<h1>Adicionar Conteúdo</h1>
<br><br>

<form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button class="btn btn-success">Publicar</button>

{% endblock %}

blog/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <title>
      {% block title %}
        Mundo do Fisiculturismo
      {% endblock %}
    </title>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <a class="navbar-brand" href="{% url 'home' %}">Mundo do Fisiculturismo</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
    
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'posts' %}">Conteúdo </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'add_post' %}">Criar Postagem</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'categories' %}">Categorias</a>
          </li>
        </ul>
      </div>
    </nav>
    
    <br>
    <div class="container">
      {% block content %}

      {% endblock %}
    </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>
</html>

blog/templates/categories.html
{% extends 'base.html' %}
{% block title%} Categorias {% endblock %}

{% block content %}

<h1>Categorias</h1>
<hr><br>
<ul> 
{% for cat in object_list %}
    <li> <a href="{% url 'category-detail' cat.id %}"><strong>{{ cat.name }}</strong> </a> 
    <br>
    {{ cat.description|slice:'150'|safe }}...
    
    <br><hr>
{% endfor %}
</ul>   

{% endblock %}

blog/templates/category_details.html
{% extends 'base.html' %}
{% block title%} Categoria: {{ cat.name }} {% endblock %}

{% block content %}

<h1>Categoria: {{ cat.name }}</h1>
<hr>

<h5>Descrição</h5>{{ cat.description }}
<br><br><br>

<h5>Postagens</h5>
<br>

<ul> 
    {% for post in cat.post_set.all %}
        <li> <a href="{% url 'post-detail' post.pk %}"><strong>{{ post.title }}</strong> </a> - 
            <small>{{ post.author.first_name}} {{post.author.last_name }}</small> <br>
            <small>{{ post.datetime }}</small></li> 
    {% endfor %}
</ul>

<br>
<a href="{% url 'categories' %}" class="btn btn-secondary">Voltar </a>

{% endblock %}

blog/templates/delete_post.html
{% extends 'base.html' %}
{% block title%} Excluir Postagem {% endblock %}

{% block content %}

<h1>Excluir Postagem</h1>
<br><br>
<h3> Excluir: {{ post.title }}</h3>

<br>
<form method="POST">
    {% csrf_token %}
    <strong>Tem certeza que deseja excluir?</strong><br> 
    <small>(Esta ação não pode ser desfeita)</small><br><br>
    <button class="btn btn-danger">Excluir</button>

{% endblock %}

blog/templates/home.html
{% extends 'base.html' %}
{% block title%} Home {% endblock %}

{% block content %}

<div class="media">
    <img src='https://st2.depositphotos.com/1012338/6218/v/600/depositphotos_62188249-stock-illustration-bodybuilding-shield.jpg' width="130" class="mr-0"> 
    <h1>Home</h1>
</div>
<hr>

Este blog é sobre fisiculturismo! <br><br>

<div class="media">
    <img src='https://musculacaoefitness.com.br/wp-content/uploads/2018/09/1-old-06.png' width="150" class="mr-2">
    <img src='https://musculacaoefitness.com.br/wp-content/uploads/2018/09/1-old-07.png' width="150" class="mr-2">
    <img src='https://musculacaoefitness.com.br/wp-content/uploads/2018/09/1-old-12.png' width="150" class="mr-2">
    <img src='https://musculacaoefitness.com.br/wp-content/uploads/2018/09/1-old-08.png' width="150" class="mr-2">
    <img src='https://musculacaoefitness.com.br/wp-content/uploads/2018/09/1-old-11.png' width="150" class="mr-2">
</div>

{% endblock %}

blog/templates/post_details.html
{% extends 'base.html' %}
{% block title%} {{ post.title }} {% endblock %}

{% block content %}

<h1>{{ post.title }}</h1>

<small> Por: {{ post.author.first_name }} {{ post.author.last_name }} <br>
    Data: {{ post.datetime }} </small>
<hr>
<small><a href="{% url 'update_post' post.pk %}" class="btn btn-info btn-sm">Editar</a> 
    <a href="{% url 'delete_post' post.pk %}" class="btn btn-danger btn-sm">Excluir</a></small><br>
<br><br>

<div class="media">
    <img src={{ post.imageURL }} width="200" class="mr-5">
    <div class="media-body">
      <p>{{ post.body|safe }}</p>
<br><br>
    </div>
</div>

<br><br>
<a href="{% url 'posts' %}" class="btn btn-secondary">Voltar </a> 

<br><hr>
<h3>Categorias</h3>

<ul>
{% if post.category.all %}
    {% for cat in post.category.all %}
        <li><a href="{% url 'category-detail' cat.id %}"> {{ cat.name }}</a> </li>
    {% endfor %}
{% endif %}
</ul>

<br><hr>
<h3>Comentários</h3>

{% if not post.comments.all %}
    <small>Ainda não há comentários para esta publicação...</small>
    <br><br>
    <a href="{% url 'add_comment' post.pk %}" class="btn btn-dark btn-sm">Adicionar Comentário</a>
    <br><br>
{% else %}
    <a href="{% url 'add_comment' post.pk %}" class="btn btn-dark btn-sm">Adicionar Comentário</a> <br><br>
    {% for comment in post.comments.all %}
        <strong>{{ comment.author.first_name }} {{ comment.author.last_name }}</strong> <small>- {{ comment.datetime }}</small>
        <br>{{ comment.body }} <br><br>
    {% endfor %}
{% endif %}

<br><hr>

{% endblock %}

blog/templates/posts.html
{% extends 'base.html' %}
{% block title%} Postagens do Blog {% endblock %}

{% block content %}

<h1>Postagens</h1>
<hr><br>
<ul> 
{% for post in object_list %}
    <li> <a href="{% url 'post-detail' post.pk %}"><strong>{{ post.title }}</strong> </a> - 
        <small>{{ post.author.first_name}} {{post.author.last_name }}</small> <br>
        <small>{{ post.datetime }}</small> <br>
        {{ post.body|slice:":290"|safe}} </li> 
        <small><a href="{% url 'update_post' post.pk %}" class="btn btn-info btn-sm">Editar</a> 
            <a href="{% url 'delete_post' post.pk %}" class="btn btn-danger btn-sm">Excluir</a></small><br><br>
{% endfor %}
</ul>

<a href="{% url 'home' %}" class="btn btn-primary">Home </a> <br><br>

{% endblock %}

blog/templates/update_post.html
{% extends 'base.html' %}
{% block title%} Editar Postagem {% endblock %}

{% block content %}

<h1>Editar Conteúdo</h1>
<br><br>

<form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button class="btn btn-success">Atualizar</button>

{% endblock %}